- name: Installer Promtail sur une VM Node.js
  hosts: nodejs_servers
  become: yes
  tasks:
    - name: Télécharger Promtail
      get_url:
        url: https://github.com/grafana/loki/releases/download/v2.9.4/promtail-linux-amd64.zip
        dest: /tmp/promtail.zip

    - name: Installer unzip
      apt:
        name: unzip
        state: present

    - name: Décompresser Promtail
      unarchive:
        src: /tmp/promtail.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Rendre Promtail exécutable
      file:
        path: /usr/local/bin/promtail-linux-amd64
        mode: '0755'

    - name: Copier la configuration Promtail
      copy:
        src: files/promtail-config.yaml
        dest: /etc/promtail/config.yaml

    - name: Créer le service systemd
      copy:
        dest: /etc/systemd/system/promtail.service
        content: |
          [Unit]
          Description=Promtail service
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/promtail-linux-amd64 -config.file=/etc/promtail/config.yaml
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Activer et démarrer Promtail
      systemd:
        name: promtail
        enabled: yes
        state: started