name: CI/CD Flutter & Node.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '22'
  FLUTTER_VERSION: '3.29.3'

jobs:
  # Tests et builds en parallèle
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: api/backend/package-lock.json
      - run: cd api/backend && npm ci --include=dev
      - run: cd api/backend && node app/scripts/initDB.js
      - run: cd api/backend && npm run test

  test-flutter:
    name: Test Flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - uses: actions/cache@v4
        with:
          path: api/mobile/.dart_tool/
          key: flutter-${{ hashFiles('api/mobile/pubspec.lock') }}
      - run: cd api/mobile && flutter pub get
      - run: cd api/mobile && flutter test

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: api/backend/package-lock.json
      - run: cd api/backend && npm ci --include=dev
      - run: cd api/backend && npm run format -- --check
      - run: cd api/backend && npm run lint

  lint-flutter:
    name: Lint Flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - uses: actions/cache@v4
        with:
          path: api/mobile/.dart_tool/
          key: flutter-${{ hashFiles('api/mobile/pubspec.lock') }}
      - run: cd api/mobile && flutter pub get
      - run: cd api/mobile && flutter analyze
      - run: cd api/mobile && dart format --set-exit-if-changed .

  build-backend:
    name: Build Backend
    needs: [test-backend, lint-backend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: api/backend/package-lock.json
      - run: cd api/backend && npm ci
      - run: cd api/backend && echo "✅ Build completed - no build script needed"

  build-flutter:
    name: Build Flutter
    needs: [test-flutter, lint-flutter]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - uses: actions/cache@v4
        with:
          path: api/mobile/.dart_tool/
          key: flutter-${{ hashFiles('api/mobile/pubspec.lock') }}
      - run: cd api/mobile && flutter pub get
      - run: cd api/mobile && flutter build apk --release